site_name: wagtailinvoices
theme: readthedocs
pages:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Template Rendering: 'template_rendering.md'
- Advanced: 'advanced.md'
- Release Notes: 'release_notes.md'